### ISSUE TITLE
Commenting in old files

### ISSUE THREAD

**Issue by kathtran** [RickyV33/JamaTrace#106]
Add headers, in-line comments for clarification, etc. for code that we wrote earlier on/anything that hasn't been commented yet.

**Comment by RickyV33** [comment]
Whatever you worked on, you should go back and comment on it.

Pagination: Ktran
Authenticate: Ruben
Validate:  Chance

**Comment by RickyV33** [comment]
Abide by JSDoc. See the landing page for info, also googles.

**Comment by ibilal** [comment]
Done

**Comment by ibilal** [comment]
done
