### ISSUE TITLE
Retrieve item descriptions from Jama

### ISSUE THREAD

**Issue by RickyV33** [RickyV33/JamaTrace#168]
Include the description for the items in getProjectItems (lib/projects.js) that is stripped of all HTML tags. It is included in the fields property and can be accessed with `item.fields.description`
Fix unittests to accommodate for this change, and update the schema as well. 
https://css-tricks.com/snippets/javascript/strip-html-tags-in-javascript/

COUPLED WITH #170

**Comment by RickyV33** [comment]
Strip images

**Comment by RickyV33** [comment]
Investigate ways to strip html

**Comment by chances** [comment]
Don't use RegEx, it doesn't cover a lot of edge cases. It's much safer to use a DOM instead. ([source](https://blog.silentsignal.eu/2014/03/07/sanitizing-input-with-regex-considered-harmful/))

Use [sanitize-html](https://www.npmjs.com/package/sanitize-html).
