### ISSUE TITLE
Add style to selected hierarchy item

### ISSUE THREAD

**Issue by RickyV33** [RickyV33/JamaTrace#176]
Currently, when you select an item form the item hierarchy list, there is nothing that tells you that you selected it. Add a class

**Comment by RickyV33** [comment]
querySelectorAll( [css selector]) to select the item with the "selected" class, then remove the class and add it to the new one for a reselect

**Comment by RickyV33** [comment]
Look at the toggle function for an idea on how to use querySelectorAll

**Comment by ibilal** [comment]
Where should the class be added? Where is the toggle function? Where does this functionality need to be added?
