### ISSUE TITLE
Add document keys to item hierarchy list

### ISSUE THREAD

**Issue by kathtran** [RickyV33/JamaTrace#183]
Grab the document key (`documentKey`) and place it in parentheses at the end of each item in the item hierarchy list that gets generated in the view.

i.e.,
`This is an item (JCP1-TXT-1)`

**Comment by RickyV33** [comment]
documentKey is a field in the items/ endpoint, so it should be quick to add

**Comment by RickyV33** [comment]
See getItemTypeImages function and the buildGraph function to see how images are being added. Performance is not a priority
