### ISSUE TITLE
Configure D3

### ISSUE THREAD

**Issue by kathtran** [RickyV33/JamaTrace#45]
The JamaTrace frontend will setup D3 to accommodate and render Item Relationship Graphs.

Configure how D3 to render a relationship graph in a SVG document given a JSON blob adhering to the Item Hierarchy( Possibility meant relationship graph JSON -Ricky) JSON Spec with nodes representing project items and edges representing the relationships between the items.

Nodes are:
* Circles with radii 5.
* Belong to the 'node' class
* Clustered with their related siblings, much like the Force-Directed Graph D3 Example minus the physics. Don't use this block: force.on("tick", function() { ... }

Don't worry about node style, i.e. fill color, stroke-width, save radii.

Edges (links) are:
* Belong to the 'edge' class
* Fixed length of: SVG width divided by 5 (width / 5)

See:
http://bl.ocks.org/sathomas/11550728 - Understanding D3.js Force Layout - 1: The Simplest Possible Graph (Model example without physics, and lots of good comments.)

http://bl.ocks.org/sathomas/11560633 - Understanding D3.js Force Layout - 2: Simple to Complex with (almost) No Code Changes
http://bl.ocks.org/mbostock/4062045 - Force-Directed Graph
http://bl.ocks.org/mbostock/4600693 - Curved Links
http://bl.ocks.org/mbostock/1093130 - Collapsible Force Layout

**Comment by ruv-prog-so** [comment]
Notes about changes:
- Icons for each item type pulled from jama
- Collapse all nodes by default
- Explode graph button (Stretch goal)
- Pinning node to canvas (stretch goal)
