### ISSUE TITLE
Create 'hierarchy' endpoint

### ISSUE THREAD

**Issue by kathtran** [RickyV33/JamaTrace#50]
As a user, I want a 'hierarchy' route so that I can select a root item from which to visualize the graph.

Create a '/hierarchy' route endpoint in the backend to handle item hierarchy related requests.

**Comment by RickyV33** [comment]
May need more info @chances @ibilal

**Comment by RickyV33** [comment]
Was there any discussion made on this? Does this need a query parameter?

**Comment by RickyV33** [comment]
@ibilal @chances Was there any discussion made on this? Does this need a query parameter?

**Comment by chances** [comment]
This endpoint should respond with a JSON blob, in the Item Hierarchy JSON format
