### ISSUE TITLE
Filter graph to only include item types for selected project (Do not do)

### ISSUE THREAD

**Issue by RickyV33** [RickyV33/JamaTrace#92]
Use the &rootOnly=true  url property to retrieve a list of all root item types used in the selected project. Then, when requesting all the items/relationships from the project, check if the item type is in the list of root item types. If it is, add it to the nodes/relationship list.

**Comment by RickyV33** [comment]
How do you know what is in the folder item types?

**Comment by RickyV33** [comment]
May need additional discussion

**Comment by ruv-prog-so** [comment]
@RickyV33 our last conversation that we had yesterday, Mike was saying that Jama did not want us to render the set types (or roots, such as Epics -> *all epic nodes*). The new information is in contradiction with this story.

**Comment by HansenML** [comment]
So the idea was to present the user with a list of sets (The folders in our Jama project) then they select one. We then show all the members of that set. Lets use epics for this example. We have a set "Epics" that we select. I render this with "Epics" as our root and it then displays all the items in that set: "User Login Homepage, Render Graph, etc..". They would like the root node to be hidden on the render screen. This means it will appear to the user that each item of the set "Epics" is a disjoint graph. They can click on one of the items and we will display it's downstream items.

**Comment by RickyV33** [comment]
@HansenML @ruv-prog-so So, when this story was written, I was under the impression that adding rootOnly=True would return a list of all the item types available to the project (which you can see if you go to Jama > Jama Software Capstone > Project > Configure Project > Item Types). The intention of this story was to filter out the folders/sets from our D3 visualization. We only want to display the item types that are included in the project. Having sets/folders in our graph without any relationships going in and out of them is pointless..

**Comment by ruv-prog-so** [comment]
Note - Need to have a type or an id passed into the graph

**Comment by kathtran** [comment]
No longer needed.
